export const SEARCH_POLICY = 'SEARCH_POLICY'
export const ADD_DOCUMENT_ITEM = 'ADD_DOCUMENT_ITEM'
export const EDIT_DOCUMENT_ITEM = 'EDIT_DOCUMENT_ITEM'
export const REMOVE_DOCUMENT_ITEM = 'REMOVE_DOCUMENT_ITEM'